<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets\spt_installer.ico</ApplicationIcon>
        <Configurations>Debug;Release;TEST</Configurations>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
        <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">2.204.0.0</AssemblyVersion>
        <FileVersion Condition="'$(FileVersion)' == ''">$(AssemblyVersion)</FileVersion>
        <Company>SPT</Company>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <None Remove=".gitignore" />
        <None Remove="Assets\spt_installer.ico" />
        <None Remove="Resources\update.ps1" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\update.ps1" />
        <None Remove="Resources\7z.dll" />
        <EmbeddedResource Include="Resources\7z.dll" />
        <None Remove="Resources\add_shortcuts.ps1" />
        <None Remove="Resources\desktop_shortcuts.ps1" />
        <EmbeddedResource Include="Resources\add_shortcuts.ps1" />
        <EmbeddedResource Include="Resources\desktop_shortcuts.ps1" />
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="Roots.xml" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
        <PackageReference Include="DialogHost.Avalonia" Version="0.12.3" />
        <PackageReference Include="DynamicData" Version="9.4.33" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="SerilogTraceListener" Version="3.2.0" />
        <PackageReference Include="Squid-Box.SevenZipSharp" Version="1.6.2.24" />
        <PackageReference Include="System.Reactive" Version="7.0.0" />
    </ItemGroup>
</Project>
