<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <Configurations>Debug;Release;TEST</Configurations>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
        <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">2.205.0.0</AssemblyVersion>
        <FileVersion Condition="'$(FileVersion)' == ''">$(AssemblyVersion)</FileVersion>
        <Company>SPT</Company>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets\spt_installer.ico</ApplicationIcon>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
        <AssemblyName>SPTInstaller.Linux</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <None Remove=".gitignore" />
        <None Remove="Assets\spt_installer.ico" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Resources\add_shortcuts.ps1" />
        <None Remove="Resources\desktop_shortcuts.ps1" />
        <EmbeddedResource Include="Resources\add_shortcuts.ps1" />
        <EmbeddedResource Include="Resources\desktop_shortcuts.ps1" />
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="Roots.xml" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="SPTInstaller.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
        <PackageReference Include="DialogHost.Avalonia" Version="0.12.3" />
        <PackageReference Include="DynamicData" Version="9.4.33" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="SerilogTraceListener" Version="3.2.0" />
        <PackageReference Include="System.Reactive" Version="7.0.0" />
        <PackageReference Include="AsmResolver.PE.Win32Resources" Version="6.0.1" />
        <PackageReference Include="SharpCompress" Version="0.50.4" />
    </ItemGroup>
</Project>
